/**
 * BandIT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const ContactType = {
    NUMBER_0: 0 as ContactType,
    NUMBER_1: 1 as ContactType,
    NUMBER_2: 2 as ContactType,
    NUMBER_3: 3 as ContactType,
    NUMBER_4: 4 as ContactType,
    NUMBER_5: 5 as ContactType,
    NUMBER_6: 6 as ContactType,
    NUMBER_7: 7 as ContactType,
    NUMBER_8: 8 as ContactType,
    NUMBER_9: 9 as ContactType
};