/**
 * BandIT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EventType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const EventType = {
    NUMBER_0: 0 as EventType,
    NUMBER_1: 1 as EventType,
    NUMBER_2: 2 as EventType,
    NUMBER_3: 3 as EventType,
    NUMBER_4: 4 as EventType,
    NUMBER_5: 5 as EventType,
    NUMBER_6: 6 as EventType,
    NUMBER_7: 7 as EventType
};