/**
 * BandIT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GearType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const GearType = {
    NUMBER_0: 0 as GearType,
    NUMBER_1: 1 as GearType,
    NUMBER_2: 2 as GearType,
    NUMBER_3: 3 as GearType,
    NUMBER_4: 4 as GearType,
    NUMBER_5: 5 as GearType,
    NUMBER_6: 6 as GearType,
    NUMBER_7: 7 as GearType,
    NUMBER_8: 8 as GearType
};