/**
 * BandIT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PositionType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const PositionType = {
    NUMBER_0: 0 as PositionType,
    NUMBER_1: 1 as PositionType,
    NUMBER_2: 2 as PositionType,
    NUMBER_3: 3 as PositionType,
    NUMBER_4: 4 as PositionType,
    NUMBER_5: 5 as PositionType,
    NUMBER_6: 6 as PositionType,
    NUMBER_7: 7 as PositionType,
    NUMBER_8: 8 as PositionType,
    NUMBER_9: 9 as PositionType
};