/**
 * BandIT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BandDto } from './bandDto';
import { UserRole } from './userRole';

export interface UserDto { 
    id?: string;
    userName?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    role: UserRole;
    band?: BandDto;
}